apiVersion: v1
kind: Secret
metadata:
  name: nlw-secret
type: Opaque
stringData:
  DB_URL: postgres://postgres:postgres@postgres-srv:5432/postgres
  REACT_APP_MAPBOX_TOKEN: pk.eyJ1Ijoib3ZlcnoiLCJhIjoiY2tnNnRjZjAyMDBxMzJwbzloOHc3bzRoNSJ9.0ZNJVbE7dHqEMVyP-3Y5Pg
